name: CI
on:
    push:
        paths-ignore:
            - "**/README.md"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: yarn install --frozen-lockfile --silent && yarn core build

            - name: Run jest tests
              run: yarn test
    cypress:
        name: Cypress tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: yarn install --frozen-lockfile --silent && yarn core build

            - name: Run cypress tests
              uses: cypress-io/github-action@v2
              env:
                  CYPRESS_BASE_URL: http://localhost:8000/admin
              with:
                  browser: chrome
                  headless: true
                  start: yarn start
                  wait-on: "http://localhost:8000/admin"
