name: CI
on:
    push:
        paths-ignore:
            - "**/README.md"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: yarn install --frozen-lockfile --silent && yarn core build

            - name: Run jest tests
              run: yarn test
    cypress:
        name: Cypress tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: yarn install --frozen-lockfile --silent && yarn build

            - name: Run cypress tests
              uses: cypress-io/github-action@v2
              env:
                  CYPRESS_BASE_URL: http://localhost:8000/admin
                  CYPRESS_API_URL: http://localhost:8000/api/v1
                  CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
                  CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
                  FIREBASE_BUCKET_NAME: ${{ secrets.FIREBASE_BUCKET_NAME }}
                  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
                  FIREBASE_CLIENT_EMAIL: ${{ secrets.CYPRESS_PASSWORD }}
                  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
                  MONGO_DB_CONNECTION: ${{ secrets.MONGO_DB_CONNECTION }}
                  REACT_APP_FCM_API_TOKEN: ${{ secrets.REACT_APP_FCM_API_TOKEN }}

              with:
                  browser: chrome
                  headless: true
                  start: yarn start
                  wait-on: "http://localhost:8000/admin"
                  config-file: packages/admin/cypress.json
                  command: yarn admin cy:run
