name: CI
on:
    push:
        paths-ignore:
            - "**/README.md"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install apt libraries
              run: sudo apt install gettext -y

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - name: Install dependencies
              run: yarn install --frozen-lockfile --silent

            - name: Run jest tests
              run: yarn test

            - name: Run typescript tests
              run: npx tsc
    cypress:
        name: Cypress tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - name: Run cypress tests
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  headless: true
                  install-command: yarn install --frozen-lockfile --silent
                  start: yarn start
                  wait-on: "localhost:8000/admin"
